# Generated by cpp11: do not edit by hand

kde_estimate <- function(fishnet, points, bw, kernel, scaled, decay, weights, showProgressBar) {
  .Call(`_SpatialKDE_kde_estimate`, fishnet, points, bw, kernel, scaled, decay, weights, showProgressBar)
}
