# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kde_estimate <- function(fishnet, points, bw, kernel, scaled = FALSE, decay = 1, weights = numeric(0)) {
    .Call('_SpatialKDE_kde_estimate', PACKAGE = 'SpatialKDE', fishnet, points, bw, kernel, scaled, decay, weights)
}

