name: Pkgdown - build and deploy website

on:
  push:
    paths:
      - R/**
      - DESCRIPTION
      - .github/workflows/build_deploy_website.yaml
      - NEWS.md

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install Linux libraries
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          sudo apt-get install libcurl4-openssl-dev

      - name: Install pkgdown sysdeps
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Cache R packages
        uses: actions/cache@v1
        if: runner.os != 'Windows'
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}

      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "devtools"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Install R package pkgdown
        run: |
          Rscript -e 'install.packages(c("pkgdown"))'

      - name: Install package
        run: R CMD INSTALL .

      - name: Set GIT
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: Document Package
        run: |
          Rscript -e "devtools::document(roclets = c('rd', 'collate', 'namespace'))"
          git commit --allow-empty -m "update docs" -a

      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package website
        run: |
          Rscript -e "pkgdown::build_site()"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs

